POST http://localhost:3030/superheroes HTTP/1.1
content-type: application/json

{
  "name": "Kal-El",
  "alias": "Superman"
}

################################

GET http://localhost:3030/superheroes HTTP/1.1

################################

PUT http://localhost:3030/superheroes/931406e3-a82a-4848-b809-5829513c8b63 HTTP/1.1
content-type: application/json

{
  "name": "Clark Kent",
  "alias": "Superman"
}

################################
DELETE http://localhost:3030/superheroes/931406e3-a82a-4848-b809-5829513c8b63 HTTP/1.1
